# Generated by Django 6.0.1 on 2026-01-24 00:03

import cookie.trails.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scout_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('grade', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'families',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('pickup', 'Pickup'), ('return', 'Return'), ('count', 'Count'), ('cookie_order', 'Cookie Order')], db_index=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_data', models.JSONField(default=cookie.trails.models._default_count_data)),
                ('unit', models.CharField(choices=[('box', 'Box'), ('case', 'Case')], default='box', max_length=10)),
                ('extra', models.JSONField(default=dict)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='trails.family')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
